import { defaultUsdToPkrRate } from "@/lib/finance/local-finance";
import { sampleLocalProjects } from "@/lib/local-data/projects";
import type { LocalDonation, LocalDonor, LocalTransfer } from "@/lib/local-data/schema";

function moneyValues(originalAmount: number, originalCurrency: "PKR" | "USD", exchangeRate: number) {
  if (originalCurrency === "PKR") {
    return {
      originalAmount,
      originalCurrency,
      exchangeRate,
      pkrAmount: originalAmount,
      usdAmount: originalAmount / exchangeRate,
    };
  }

  return {
    originalAmount,
    originalCurrency,
    exchangeRate,
    pkrAmount: originalAmount * exchangeRate,
    usdAmount: originalAmount,
  };
}

export const sampleLocalDonations: LocalDonation[] = [
  {
    id: "donation-1",
    donorId: "donor-1",
    donorName: "Al Noor Group",
    projectId: "project-food-parcels",
    project: "Food Parcels",
    accountId: "main-donations-bank",
    method: "Bank Transfer",
    date: "2026-07-11",
    status: "Received",
    receiptReference: "DON-0001",
    notes: "Sample donation for Food Parcels.",
    ...moneyValues(12500, "USD", defaultUsdToPkrRate),
  },
  {
    id: "donation-2",
    donorId: "donor-2",
    donorName: "Sarah Malik",
    projectId: "project-hospital",
    project: "Hospital Project",
    accountId: "main-donations-bank",
    method: "Card",
    date: "2026-07-11",
    status: "Received",
    receiptReference: "DON-0002",
    notes: "Sample hospital donation.",
    ...moneyValues(2000, "USD", defaultUsdToPkrRate),
  },
  {
    id: "donation-3",
    donorId: "donor-3",
    donorName: "Rahman Family Trust",
    projectId: "project-orphan-sponsorship",
    project: "Orphan Sponsorship",
    accountId: "main-donations-bank",
    method: "Cheque",
    date: "2026-07-10",
    status: "Processing",
    receiptReference: "DON-0003",
    notes: "Sample pledge under processing.",
    ...moneyValues(25000, "USD", defaultUsdToPkrRate),
  },
  {
    id: "donation-4",
    donorId: "donor-4",
    donorName: "Green Crescent LLC",
    projectId: "project-daily-iftar",
    project: "Daily Iftar",
    accountId: "main-donations-bank",
    method: "Bank Transfer",
    date: "2026-07-09",
    status: "Received",
    receiptReference: "DON-0004",
    notes: "Sample iftar donation.",
    ...moneyValues(8750, "USD", defaultUsdToPkrRate),
  },
];

export const sampleLocalTransfers: LocalTransfer[] = [
  {
    id: "transfer-1",
    fromAccountId: "main-donations-bank",
    toAccountId: "field-cash-pkr",
    projectId: "project-general-operations",
    project: "Field Operations",
    date: "2026-07-12",
    status: "Scheduled",
    reference: "TRF-0001",
    notes: "Sample transfer to field cash.",
    ...moneyValues(18000, "USD", defaultUsdToPkrRate),
  },
  {
    id: "transfer-2",
    fromAccountId: "main-donations-bank",
    toAccountId: "operations-bank-pkr",
    projectId: "project-hospital",
    project: "Hospital Project",
    date: "2026-07-10",
    status: "Completed",
    reference: "TRF-0002",
    notes: "Sample allocation to Hospital Project.",
    ...moneyValues(22500, "USD", defaultUsdToPkrRate),
  },
  {
    id: "transfer-3",
    fromAccountId: "main-donations-bank",
    toAccountId: "operations-bank-pkr",
    projectId: "project-orphan-sponsorship",
    project: "Orphan Sponsorship",
    date: "2026-07-08",
    status: "Completed",
    reference: "TRF-0003",
    notes: "Sample allocation to Orphan Sponsorship.",
    ...moneyValues(15000, "USD", defaultUsdToPkrRate),
  },
];

export const sampleLocalDonors: LocalDonor[] = [
  {
    id: "donor-1",
    fullName: "Al Noor Group",
    phone: "+92 300 1111111",
    whatsapp: "+92 300 1111111",
    email: "partnerships@alnoor.example",
    country: "Pakistan",
    preferredContactMethod: "Email",
    donorType: "Corporate",
    givingPreferences: ["Food Parcels", "Emergency Aid"],
    zakatPreference: "General zakat eligible causes",
    recurringDonor: true,
    notes: "Corporate donor with seasonal campaign support.",
    taxReceiptStatus: "Issued",
    updateHistory: [{ id: "update-1", date: "2026-07-09", summary: "Sent monthly impact note." }],
    nextUpdateDueDate: "2026-07-25",
    reminderStatus: "Upcoming",
  },
  {
    id: "donor-2",
    fullName: "Sarah Malik",
    phone: "+1 312 555 0101",
    whatsapp: "+1 312 555 0101",
    email: "sarah@example.com",
    country: "United States",
    preferredContactMethod: "WhatsApp",
    donorType: "Individual",
    givingPreferences: ["Hospital"],
    zakatPreference: "Medical aid only",
    recurringDonor: true,
    notes: "Prefers concise updates with patient stories.",
    taxReceiptStatus: "Pending",
    updateHistory: [{ id: "update-2", date: "2026-07-05", summary: "Shared hospital procurement update." }],
    nextUpdateDueDate: "2026-07-20",
    reminderStatus: "Upcoming",
  },
  {
    id: "donor-3",
    fullName: "Rahman Family Trust",
    phone: "+44 20 7946 0000",
    whatsapp: "+44 7700 900123",
    email: "contact@rahmantrust.example",
    country: "United Kingdom",
    preferredContactMethod: "Email",
    donorType: "Foundation",
    givingPreferences: ["Orphan Sponsorship", "Education"],
    zakatPreference: "Annual zakat pool",
    recurringDonor: false,
    notes: "Requests formal reports and trustee-level summaries.",
    taxReceiptStatus: "Issued",
    updateHistory: [{ id: "update-3", date: "2026-07-08", summary: "Queued pledge follow-up." }],
    nextUpdateDueDate: "2026-07-18",
    reminderStatus: "Upcoming",
  },
  {
    id: "donor-4",
    fullName: "Green Crescent LLC",
    phone: "+971 4 555 0101",
    whatsapp: "+971 50 555 0101",
    email: "omar@greencrescent.example",
    country: "United Arab Emirates",
    preferredContactMethod: "Phone",
    donorType: "Corporate",
    givingPreferences: ["Daily Iftar", "Food Parcels"],
    zakatPreference: "Ramadan giving",
    recurringDonor: false,
    notes: "New relationship; prefers direct calls before email summaries.",
    taxReceiptStatus: "Not Required",
    updateHistory: [{ id: "update-4", date: "2026-07-10", summary: "Introductory stewardship call logged." }],
    nextUpdateDueDate: "2026-07-16",
    reminderStatus: "Upcoming",
  },
];

export { sampleLocalProjects };
